const quotes = [
  { text: "Il tempo è ciò che diamo in cambio a ciò che scegliamo di diventare.", author: "Carlos Castaneda — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Diventa così bravo in ciò che fai… che non possano ignorarti.", author: "Steve Martin // "Le persone forti non sono quelle che non cadono mai, ma quelle che si rialzano ogni volta che cadono." - Confucio — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Sii paziente con te stesso. La crescita interiore è un lavoro silenzioso e profondo.", author: "Sandra Carey — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non smettere mai di fare del tuo meglio solo perché qualcuno non ti dà credito.", author: "Kamari aka Lyrikal — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La vita si restringe o si espande in proporzione al coraggio di ciascuno.", author: "Anaïs Nin — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Ritagliati del tempo per essere semplicemente felice. Non è una fuga, è una forma di guarigione.", author: "Brianna Wiest — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non è necessario vedere l’intera scala. Inizia semplicemente a salire il primo gradino.", author: "Martin Luther King Jr. — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La disciplina è scegliere tra ciò che vuoi ora e ciò che vuoi di più.", author: "Abraham Lincoln — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non aspettare. Il tempo non sarà mai giusto.", author: "Napoleon Hill — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non aspettare il momento perfetto. Coglilo e rendilo perfetto", author: "George Bernard Shaw — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Le difficoltà rafforzano la mente, come la fatica rafforza il corpo.", author: "Lucio Anneo Seneca — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non è perché le cose sono difficili che non osiamo farle, è perché non osiamo farle che sono difficili.", author: "Lucio Anneo Seneca — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Fai quello che puoi, con quello che hai, nel posto in cui sei.", author: "Theodore Roosevelt — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.", author: "Eleanor Roosevelt — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non possiamo diventare ciò che vogliamo essere restando ciò che siamo.", author: "Max De Pree — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Abbi il coraggio di seguire il tuo cuore e la tua intuizione. In qualche modo, loro sanno già cosa vuoi veramente diventare.", author: "Steve Jobs — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Expose yourself to your deepest fear; after that, fear has no power...", author: "Jim Morrison — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Ci sono due giorni all’anno ... vivere.", author: "Dalai Lama — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Fai della tua vita un sogno, e di un sogno, una realtà.", author: "Antoine de Saint-Exupéry — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La libertà è come l’aria...", author: "Piero Calamandrei — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Il talento ti fa vincere una partita...", author: "Michael Jordan — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Insegna con l’esempio...", author: "Ralph Waldo Emerson — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Un buon insegnante è come una candela...", author: "Mustafa Kemal Atatürk — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La mia missione nella vita...", author: "Maya Angelou — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La felicità non è qualcosa di pronto...", author: "Tenzin Gyatso, Dalai Lama — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Ogni nuovo inizio viene da qualche altro inizio...", author: "Seneca — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "L’uomo non può scoprire nuovi oceani...", author: "André Gide — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Coltiva le tue inclinazioni interiori...", author: "Carl Gustav Jung — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "L’arte di ispirare...", author: "Harold Whitman — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“La serenità non è essere al riparo...", author: "Thomas More — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“The only limit to our realization of tomorrow...", author: "Franklin D. Roosevelt — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“Fate il vostro dovere nel piccolo...", author: "Peter Drucker — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“Non aver paura della lentezza...", author: "Proverbio cinese — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“Tutti pensano a cambiare il mondo...", author: "Lev Tolstoj — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“Colui che ha un perché...", author: "Friedrich Nietzsche — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“Il mondo cambia con il tuo esempio...", author: "Paulo Coelho — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“Un fiammifero può accendere...", author: "Chimamanda Ngozi Adichie — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“L’oceano è fatto di gocce...", author: "Vandana Shiva — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“Coloro che amano camminare da soli...", author: "Matshona Dhliwayo — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Un popolo che non conosce la propria storia...", author: "George Santayana — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“La cosa più difficile è decidere di agire...", author: "Amelia Earhart — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“Se non puoi amare te stesso...", author: "RuPaul — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La vera libertà individuale...", author: "Franklin D. Roosevelt — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non si può scoprire nuovi oceani...", author: "André Gide — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La conoscenza è potere...", author: "Kofi Annan — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La misura definitiva dell’uomo...", author: "Martin Luther King Jr. — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La libertà non consiste nel fare ciò che ci piace...", author: "Giovanni Paolo II — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Le persone straordinarie non nascono...", author: "Robin Sharma — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non temere la perfezione...", author: "Salvador Dalí — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "“L’unico vero fallimento...", author: "Brené Brown — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Il miglior modo per predire il futuro...", author: "Peter Drucker — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non smettere mai di cercare...", author: "Paulo Coelho — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Colui che conosce gli altri...", author: "Lao Tzu — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "Non cercare l’amore fuori di te...", author: "Debbie Ford — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
  { text: "La vita si restringe...", author: "Anaïs Nin — Wakeify", note: "Scegli oggi un'azione che renda concreta questa idea." },
];
export default quotes;
